apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: soc_alerts
    user: mlsecops
    secureJsonData:
      password: supersecret
    jsonData:
      sslmode: disable
      postgresVersion: 15
    isDefault: true
